# Generated by Django 5.2.13 on 2026-05-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('experience', models.PositiveIntegerField(default=1, verbose_name='Опыт (лет)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Фото инструктора')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='gym.gym', verbose_name='Название зала')),
            ],
        ),
    ]
