# Generated by Django 5.2.13 on 2026-05-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='training.training', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user_profile.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
                'unique_together': {('user', 'training')},
            },
        ),
    ]
