# Generated by Django 5.2.13 on 2026-05-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='training.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
            },
        ),
    ]
