# Generated by Django 5.2.13 on 2026-05-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user_profile.userprofile', verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrecord',
            unique_together={('user', 'training', 'date')},
        ),
    ]
