# Generated by Django 5.2.13 on 2026-05-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес зала')),
                ('open', models.TimeField(default='08:00', verbose_name='Открытие')),
                ('close', models.TimeField(default='22:00', verbose_name='Закрытие')),
                ('contact_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание зала')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gyms/', verbose_name='Фото зала')),
            ],
            options={
                'verbose_name': 'Зал (филиал)',
                'verbose_name_plural': 'Залы (филиалы)',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_list', to='gym.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_list', to='gym.gym')),
            ],
        ),
    ]
