# Generated by Django 5.2.13 on 2026-04-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название тренировки')),
                ('training_time', models.TimeField(verbose_name='Время тренировки')),
                ('start_of_recording', models.TimeField(verbose_name='Начало записи')),
                ('activation', models.BooleanField(default=True, verbose_name='Активна')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='gym.gym', verbose_name='Зал')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor', verbose_name='Инструктор')),
            ],
        ),
    ]
